### ISSUE TITLE
FUSE tests hanging locally

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-fuse#56] opened 2022-02-02 15:37 UTC
I'm not entirely sure when this started (I think it was around the middle of January), but if I try to run this project's complete test suite on my Debian VM (even after updating the image and reprovisioning), the tests eventually hang indefinitely in the middle of the FUSE tests — specifically, at the first [`test_fuse_subdataset`](https://github.com/datalad/datalad-fuse/blob/69d10f96ce29df9c7462d081f5622abf7b1cfba9/datalad_fuse/tests/test_fuse.py#L32) test.  Inserting print statements reveals that the code is hanging at the `p.wait()` after `p.terminate()`.  Inspecting the process table during a hang shows that numerous datalad process from previous tests in the same run (which should have been terminated) are still running, some with `git-annex` subprocesses:

<details>
<summary><code>pstree -spla</code> output</summary>

```
systemd,1
  `-sshd,544
      `-sshd,11700
          `-sshd,11707
              `-bash,11708
                  `-screen,11746
                      `-screen,11747
                          `-bash,11748
                              `-tox,180979 /home/vagrant/.local/bin/tox -e py3 -- --libfuse -vv -k test_fuse -s
                                  `-pytest,181009 /home/vagrant/datalad-fuse/.tox/py3/bin/pytest --libfuse -vv -k test_fuse -s datalad_fuse
                                      |-datalad,181821 /home/vagrant/datalad-fuse/.tox/py3/bin/datalad fusefs -d /tmp/pytest-of-vagrant/pytest-7/url_dataset0/ds --foreground /tmp/pytest-of-vagrant/pytest-7/test_fuse_remote_False_0
                                      |   |-{datalad},181944
                                      |   |-{datalad},181945
                                      |   `-{datalad},181947
                                      |-datalad,182883 /home/vagrant/datalad-fuse/.tox/py3/bin/datalad fusefs -d /tmp/pytest-of-vagrant/pytest-7/url_dataset1/ds --foreground /tmp/pytest-of-vagrant/pytest-7/test_fuse_remote_True_0 --mode-transparent
                                      |   |-{datalad},183006
                                      |   |-{datalad},183007
                                      |   `-{datalad},183010
                                      |-datalad,184389 /home/vagrant/datalad-fuse/.tox/py3/bin/datalad fusefs -d /tmp/pytest-of-vagrant/pytest-7/url_dataset2/ds --foreground /tmp/pytest-of-vagrant/pytest-7/test_fuse_local_False_0
                                      |   |-{datalad},184512
                                      |   |-{datalad},184513
                                      |   `-{datalad},184514
                                      |-datalad,185753 /home/vagrant/datalad-fuse/.tox/py3/bin/datalad fusefs -d /tmp/pytest-of-vagrant/pytest-7/url_dataset3/ds --foreground /tmp/pytest-of-vagrant/pytest-7/test_fuse_local_True_0 --mode-transparent
                                      |   |-{datalad},185876
                                      |   `-{datalad},185877
                                      |-datalad,187635 /home/vagrant/datalad-fuse/.tox/py3/bin/datalad fusefs -d /tmp/pytest-of-vagrant/pytest-7/url_dataset4/clone --foreground /tmp/pytest-of-vagrant/pytest-7/test_fuse_cloned_False_0
                                      |   |-git,187814 --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git -c diff.ignoreSubmodules=none annex examinekey --format=annex/objects/${hashdirmixed}${key}/${key}\\n --batch
                                      |   |   `-git-annex,187829 --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git-annex/git-annex examinekey --format=annex/objects/${hashdirmixed}${key}/${key}\\n --batch
                                      |   |       |-{git-annex},187830
                                      |   |       |-{git-annex},187831
                                      |   |       |-{git-annex},187832
                                      |   |       `-{git-annex},187834
                                      |   |-git,187835 --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git -c diff.ignoreSubmodules=none annex examinekey --format=annex/objects/${hashdirlower}${key}/${key}\\n --batch
                                      |   |   `-git-annex,187850 --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git-annex/git-annex examinekey --format=annex/objects/${hashdirlower}${key}/${key}\\n --batch
                                      |   |       |-{git-annex},187851
                                      |   |       |-{git-annex},187852
                                      |   |       |-{git-annex},187853
                                      |   |       `-{git-annex},187855
                                      |   |-{datalad},187758
                                      |   |-{datalad},187759
                                      |   |-{datalad},187760
                                      |   `-{datalad},187946
                                      |-datalad,189703 /home/vagrant/datalad-fuse/.tox/py3/bin/datalad fusefs -d /tmp/pytest-of-vagrant/pytest-7/url_dataset5/clone --foreground /tmp/pytest-of-vagrant/pytest-7/test_fuse_cloned_True_0 --mode-transparent
                                      |   |-git,189882 --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git -c diff.ignoreSubmodules=none annex examinekey --format=annex/objects/${hashdirmixed}${key}/${key}\\n --batch
                                      |   |   `-git-annex,189897 --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git-annex/git-annex examinekey --format=annex/objects/${hashdirmixed}${key}/${key}\\n --batch
                                      |   |       |-{git-annex},189898
                                      |   |       |-{git-annex},189899
                                      |   |       |-{git-annex},189900
                                      |   |       `-{git-annex},189902
                                      |   |-git,189903 --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git -c diff.ignoreSubmodules=none annex examinekey --format=annex/objects/${hashdirlower}${key}/${key}\\n --batch
                                      |   |   `-git-annex,189918 --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git-annex/git-annex examinekey --format=annex/objects/${hashdirlower}${key}/${key}\\n --batch
                                      |   |       |-{git-annex},189919
                                      |   |       |-{git-annex},189920
                                      |   |       |-{git-annex},189921
                                      |   |       `-{git-annex},189923
                                      |   |-{datalad},189826
                                      |   |-{datalad},189827
                                      |   |-{datalad},189828
                                      |   `-{datalad},189954
                                      |-datalad,191766 /home/vagrant/datalad-fuse/.tox/py3/bin/datalad fusefs -d /tmp/pytest-of-vagrant/pytest-7/superdataset0 --foreground /tmp/pytest-of-vagrant/pytest-7/test_fuse_subdataset_remote_Fa0
                                      |   |-{datalad},191888
                                      |   |-{datalad},191889
                                      |   |-{datalad},191925
                                      |   `-{datalad},192007
                                      |-pytest,181051 /home/vagrant/datalad-fuse/.tox/py3/bin/pytest --libfuse -vv -k test_fuse -s datalad_fuse
                                      |   `-{pytest},181052
                                      |-(pytest,189309)
                                      `-{pytest},183702
```
</details>

The child processes are all cleaned up if I kill pytest with Control-C.

If I add a `p.wait()` to the end of `test_fuse` after `p.terminate()`, that test starts hanging.

Starting a `datalad fusefs` process normally in a terminal and killing it with `kill -s TERM` works.

None of this occurs when the tests are run under GitHub Actions.

@yarikoptic Do you have any ideas why datalad isn't terminating properly?

**Comment by yarikoptic** [comment] 2022-02-02 20:28
nothing immediate/conclusive:
- the only one which comes in mind is  https://github.com/datalad/datalad/issues/5465 which, even though relates to ssh, so not relevant here presumably.  Also we had some gotchas at git-annex level on termination of batched processes, in particular on windows, but that was hopefully fixed long ago.
- I also experienced hanging in this test, but I attributed it to erroring out code, and then whenever it was fixed had a clean run (I think).
- moreover I found over a dozen of processes running on my laptop ATM as well, killed them

you could set DATALAD_LOG_TARGET to point to a file (https://github.com/datalad/datalad/pull/4930 could be useful to get a file per PID) and run with some DATALAD_LOG_LEVEL=1 to see if any information (e.g. that received TERM) is logged in those datalad processes to pin point the problem.

may be we should wait with some timeout (e.g. 2 seconds) and then `.kill`?  Or may be even just `kill` right away -- I don't think there should be any side-effects from killing those processes operating on some temp paths

**Comment by yarikoptic** [comment] 2022-02-02 20:54
FWIW did a full run of `pytest -s -v --libfuse datalad_fuse` locally on 0.1.0-30-g99f4c21 (of #57) which did not fail/error out anything and no processes were left behind. datalad was 0.15.3  (upgaded now to 0.15.4)

**Comment by jwodder** [comment] 2022-02-08 15:19
@yarikoptic I tried setting `DATALAD_LOG_TARGET` and `DATALAD_LOG_LEVEL=1` on the `fusefs` processes run for the tests, but there doesn't seem to be any relevant information in the logs.  Here are the logs for one of the stuck processes:

https://gist.github.com/jwodder/9241ac1e1bf9724013c0eed6e52dd7c1

**Comment by yarikoptic** [comment] 2022-02-08 16:00
Thanks for digging!  
- did datalad-fuse tests complete without error/fail?
- Does child stuck (datalad) process  have any `git`/`git-annex` stuck process? is its PID logged in that log you reference?

**Comment by jwodder** [comment] 2022-02-08 16:06
> did datalad-fuse tests complete without error/fail?

Up until the one that got stuck, yes.

> Does child stuck (datalad) process have any git/git-annex stuck process?

No.  The only children listed by `pstree` are of the form `{datalad},11920`, which I think means it's a thread.

> is its PID logged in that log you reference?

The Datalad process does not log its own PID.  All of the child processes that it did log exited with 0.

**Comment by yarikoptic** [comment] 2022-02-08 16:10
could you please let me know exact invocation (tox vs direct pytest?) and what version of git/git-annex/datalad (or just output of `datalad wtf --flavor short` you have -- I will try to reproduce and dig as well.

I have just ran `python -m pytest -s -v datalad_fuse` on 0.1.0-35-gfd2e16b (current master) with 
```
$> datalad wtf --flavor short         
# WTF
- datalad: version=0.15.4
- dependencies: cmd:git=2.30.2 cmd:annex=8.20211231+git140-gc3817495f-1~ndall+1 cmd:bundled-git=2.30.2 cmd:system-git=2.34.1 cmd:system-ssh=8.7p1 cmd:7z=16.02 annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 humanize=3.11.0 iso8601=0.1.16 keyring=23.2.1 keyrings.alt=UNKNOWN msgpack=1.0.2 requests=2.26.0 wrapt=1.12.1
```
and it completed without stalling.  Running plain `tox` now.

**Comment by jwodder** [comment] 2022-02-08 18:32
@yarikoptic 

* Clone the repo and `cd` into it.
* Run `vagrant up`
* Run `vagrant ssh` to enter
* When done, run `vagrant destroy`.

**Comment by yarikoptic** [comment] 2022-02-08 18:52
FWIW, I think running it through `tox` has an effect on making stall more consistent. Seems to stall on `datalad_fuse/tests/test_fuse.py::test_fuse_subdataset[remote-False-None]` all the time.  When running directly via pytest -- nope.

**Comment by jwodder** [comment] 2022-02-08 19:08
@yarikoptic I tried running the tests by invoking pytest directly in a virtualenv created with virtualenvwrapper, and it still stalled.

**Comment by yarikoptic** [comment] 2022-02-08 19:50
may be it is a goose chaise, but FWIW, here are two `pip` freezes, which produce env in which it stalls and in which it doesn't:

http://www.onerussian.com/tmp/outside-stalling.pip-freeze
http://www.onerussian.com/tmp/outside-nonstalling.pip-freeze

installing nonstalling into a venv initiated with `stalling` first (to somewhat minimize the diff) and resulting in 

http://www.onerussian.com/tmp/outside-stalling+nonstalling.pip-freeze

resolves the stall for me.

**Comment by yarikoptic** [comment] 2022-02-08 19:56
<details>
<summary>it seems that stalling relates to some of these upgrades</summary> 

```shell
(git)lena:~datalad/datalad-fuse[master]
$> pip install -r /tmp/outside-stalling.pip-freeze.install    
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.2 MB)
Requirement already satisfied: aiosignal==1.2.0 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from -r /tmp/outside-stalling.pip-freeze.install (line 2)) (1.2.0)
Requirement already satisfied: alabaster==0.7.12 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from -r /tmp/outside-stalling.pip-freeze.install (line 3)) (0.7.12)
Requirement already satisfied: annexremote==1.5.0 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from -r /tmp/outside-stalling.pip-freeze.install (line 4)) (1.5.0)
Requirement already satisfied: appdirs==1.4.4 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from -r /tmp/outside-stalling.pip-freeze.install (line 5)) (1.4.4)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attrs==21.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Requirement already satisfied: Babel==2.9.1 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from -r /tmp/outside-stalling.pip-freeze.install (line 8)) (2.9.1)
Requirement already satisfied: beautifulsoup4==4.10.0 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from -r /tmp/outside-stalling.pip-freeze.install (line 9)) (4.10.0)
Requirement already satisfied: boto==2.49.0 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from -r /tmp/outside-stalling.pip-freeze.install (line 10)) (2.49.0)
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting cffi==1.15.0
  Using cached cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
Requirement already satisfied: chardet==4.0.0 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from -r /tmp/outside-stalling.pip-freeze.install (line 13)) (4.0.0)
Collecting charset-normalizer==2.0.11
  Using cached charset_normalizer-2.0.11-py3-none-any.whl (39 kB)
Collecting coverage==6.3.1
  Using cached coverage-6.3.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (210 kB)
Collecting cryptography==36.0.1
  Using cached cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from aiohttp==3.8.1->-r /tmp/outside-stalling.pip-freeze.install (line 1)) (1.6.3)
Requirement already satisfied: frozenlist>=1.1.1 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from aiohttp==3.8.1->-r /tmp/outside-stalling.pip-freeze.install (line 1)) (1.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from aiohttp==3.8.1->-r /tmp/outside-stalling.pip-freeze.install (line 1)) (5.1.0)
Requirement already satisfied: future in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from annexremote==1.5.0->-r /tmp/outside-stalling.pip-freeze.install (line 4)) (0.18.2)
Requirement already satisfied: pytz>=2015.7 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from Babel==2.9.1->-r /tmp/outside-stalling.pip-freeze.install (line 8)) (2021.3)
Requirement already satisfied: soupsieve>1.2 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from beautifulsoup4==4.10.0->-r /tmp/outside-stalling.pip-freeze.install (line 9)) (2.3.1)
Requirement already satisfied: pycparser in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from cffi==1.15.0->-r /tmp/outside-stalling.pip-freeze.install (line 12)) (2.20)
Requirement already satisfied: idna>=2.0 in ./venvs/dev3-pipinstallstalling/lib/python3.9/site-packages (from yarl<2.0,>=1.0->aiohttp==3.8.1->-r /tmp/outside-stalling.pip-freeze.install (line 1)) (3.2)
Installing collected packages: charset-normalizer, cffi, attrs, async-timeout, cryptography, coverage, certifi, aiohttp
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 2.0.5
    Uninstalling charset-normalizer-2.0.5:
      Successfully uninstalled charset-normalizer-2.0.5
  Attempting uninstall: cffi
    Found existing installation: cffi 1.14.6
    Uninstalling cffi-1.14.6:
      Successfully uninstalled cffi-1.14.6
  Attempting uninstall: attrs
    Found existing installation: attrs 21.2.0
    Uninstalling attrs-21.2.0:
      Successfully uninstalled attrs-21.2.0
  Attempting uninstall: async-timeout
    Found existing installation: async-timeout 3.0.1
    Uninstalling async-timeout-3.0.1:
      Successfully uninstalled async-timeout-3.0.1
  Attempting uninstall: cryptography
    Found existing installation: cryptography 3.4.8
    Uninstalling cryptography-3.4.8:
      Successfully uninstalled cryptography-3.4.8
  Attempting uninstall: coverage
    Found existing installation: coverage 5.5
    Uninstalling coverage-5.5:
      Successfully uninstalled coverage-5.5
  Attempting uninstall: certifi
    Found existing installation: certifi 2021.5.30
    Uninstalling certifi-2021.5.30:
      Successfully uninstalled certifi-2021.5.30
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.7.4.post0
    Uninstalling aiohttp-3.7.4.post0:
      Successfully uninstalled aiohttp-3.7.4.post0
Successfully installed aiohttp-3.8.1 async-timeout-4.0.2 attrs-21.4.0 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.11 coverage-6.3.1 cryptography-36.0.1
```
</details>

**Comment by jwodder** [comment] 2022-02-08 20:04
@yarikoptic `coverage` seems to be the problem.  Downgrading to `coverage<6` lets me run the tests successfully without any stalling.

**Comment by yarikoptic** [comment] 2022-02-08 20:05
confirming that too
```
$> pip install coverage==6.3.1            
Collecting coverage==6.3.1
  Using cached coverage-6.3.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (210 kB)
Installing collected packages: coverage
  Attempting uninstall: coverage
    Found existing installation: coverage 5.5
    Uninstalling coverage-5.5:
      Successfully uninstalled coverage-5.5
Successfully installed coverage-6.3.1
```
causes the stall for me.  Please troubleshoot deeper to report against coverage, we can restrict version here for now

**Comment by yarikoptic** [comment] 2022-02-08 20:10
just FTR: installing datalad master (0.15.4-660-ge1dd96530) doesn't resolve anything magically (thought just to check if may be something in coverage just started to trigger some issue we fixed in master)

**Comment by jwodder** [comment] 2022-02-08 20:12
@yarikoptic The problem may instead lie with the pytest-cov plugin used to integrate coverage with pytest.  If I comment out the "addopts" line in `tox.ini` and run `coverage run -m pytest ...` using the latest `coverage`, everything works, but using `pytest-cov` (both version `~=2.0` and the latest 3.0) lead to a stall.

**Comment by jwodder** [comment] 2022-02-08 20:52
@yarikoptic `coverage` versions that stall & don't stall when running with `pytest-cov`:

* 5.5 — no stall
* 6.0 — no stall
* 6.2 — no stall
* 6.3 — stall
* 6.3.1 — stall

I suspect the critical change in 6.3 is [the third feature mentioned here](https://coverage.readthedocs.io/en/6.3.1/changes.html#version-6-3-2022-01-25):

> coverage measurement data will now be written when a SIGTERM signal is received by the process. This includes `Process.terminate`, and other ways to terminate a process.

**Comment by jwodder** [comment] 2022-02-08 21:16
@yarikoptic Looks like this has already been reported: https://github.com/nedbat/coveragepy/issues/1310

**Comment by yarikoptic** [comment] 2022-02-08 22:28
Great, nice digging! The issue seems to being actively troubleshooted.

**Closed** 2022-02-11 22:10 UTC
